DIT-2783 Correspondence case header
hmrc/tariff-classification-frontend pull request #578
Opened 2021-03-18 16:44 UTC by shiromi

2021-03-18 17:01 UTC, periklas approved these changes

2021-03-19 08:43 UTC, ansahdavid approved these changes

2021-03-24 12:57 UTC, vajarova requested changes

2021-03-24 12:57 UTC, vajarova commented on conf/messages
> -case.v2.correspondence.page_title=Correspondence case details
can we keep those (misc and corrie and liability) the same as per Eszter's comment on the ticket please

2021-03-25 08:30 UTC, vajarova approved these changes

2021-03-25 08:31 UTC, merged