DDCE-3736 Update CSP
hmrc/tariff-classification-frontend pull request #656
Opened 2023-04-24 15:05 UTC by mywyau

2023-04-25 12:40 UTC, mywyau commented
**As an update:** 
Refactored the javascript to be out of the component and moved into the relevant view. The two blocked was the remove key word link and checkbox filters on advanced search page as shown above. Using event listener instead and adding a nonce to the script tag to comply with new CSP.

2023-05-03 12:06 UTC, EdCope requested changes
CSP was blocking backlinks.
Print inline script also affected under reports sections
File uploads working differently on this one so are ok

2023-05-04 11:02 UTC, EdCope commented on app/models/CaseReferral.scala
> +  val function1 = (x: Int) => x + 1
Remove here

2023-05-05 11:27 UTC, EdCope approved these changes

2023-05-05 11:27 UTC, merged