DDCE-5761 - Bootstrap 9.0 upgrades, cleanup code, remove scalastyle, …
hmrc/tariff-classification-frontend pull request #683
Opened 2024-08-05 10:45 UTC by frikit

…fixed scala warnings

2024-08-13 07:05 UTC, EdCope requested changes

2024-08-15 13:05 UTC, Taiwo-AB commented
All good from me @EdCope for the last two commits. All required updates have been made now 👍

2024-08-15 13:06 UTC, Taiwo-AB approved these changes

2024-08-15 13:08 UTC, EdCope approved these changes

2024-08-15 13:08 UTC, merged